### ISSUE TITLE
TS type errors with latest changes

### ISSUE THREAD

**Issue by CarterLi** [adaltas/node-csv#306] opened 2021-11-24 02:00 UTC
The latest change doesn't work well with TypeScript

```
Compiled with problems:

ERROR in src/views/data-manage/dictionary-manage/create-edit-modal/create-edit-modal.ts:1:35

TS2307: Cannot find module 'csv-parse/browser/esm/sync' or its corresponding type declarations.
  > 1 | import { parse as csvParse } from 'csv-parse/browser/esm/sync';
      |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 | import { Form } from 'element-ui';
    3 |
    4 | import { DictionaryApi } from '@/apis';
```

Can be work around with:

```ts
declare module 'csv-parse/browser/esm/sync' {
  export * from 'csv-parse/dist/esm/sync';
}
```

Why not export `csv-parse/dist/*` directly?

Ref: https://github.com/adaltas/node-csv/issues/302#issuecomment-975037165

**Comment by wdavidw** [comment] 2021-11-24 08:57
I managed to TypeScript and webpack work together, but it is sort of ugly. Because TS doesn't honors `.cjs`, I have to create a copy of `./dist/cjs/index.cjs` into `./dist/cjs/index.js` (with some additions to package.json). I hope to have more time in the coming days to find a clean fix.

**Comment by CarterLi** [comment] 2021-11-24 09:04
Why not export `csv-parse/dist/*` directly?

**Comment by CarterLi** [comment] 2021-11-24 09:07
> I managed to TypeScript and webpack work together, but it is sort of ugly. Because TS doesn't honors `.cjs`, I have to create a copy of `./dist/cjs/index.cjs` into `./dist/cjs/index.js` (with some additions to package.json). I hope to have more time in the coming days to find a clean fix.

TypeScript only cares `*.d.ts`, but doesn't care `*.cjs` or something. Webpack cares it.

**Comment by wdavidw** [comment] 2021-11-24 09:15
Not so sure, renaming the file to .js make it works. Maybe is it also related to the `export` directive. If interested, I can push the code to a branch. Maybe you'll come up with a better solution than mine.

**Comment by ivanoats** [comment] 2021-12-02 04:50
I can reproduce this also. Details in this gist: https://gist.github.com/ivanoats/62c19279db26e2d4c1db9f504e7ff270 - would love to know a work-around if one exists. Thank you for working on this!

**Comment by ivanoats** [comment] 2021-12-02 19:53
@CarterLi could you please tell me where / which file you put the work-around code in? Thanks.

**Comment by CarterLi** [comment] 2021-12-03 05:24
> @CarterLi could you please tell me where / which file you put the work-around code in? Thanks.

`*.d.ts`. The path doesn't matter.

**Comment by ivanoats** [comment] 2021-12-06 18:15
I could not get the work-around to work. I tried creating a types.d.ts file in the root of my project, but still the same error.

**Comment by wdavidw** [comment] 2021-12-13 21:27
I created the branch [feat/webpack_ts](https://github.com/adaltas/node-csv/tree/feat/webpack_ts) with a `webpack` + TypeScript demo. `webpack` is configured with Node.js polyfill, I hope this is not a problem for you. Other than this, it works pretty and doesn't involve extra complexity. Removing the polyfill requirement involves the creation of a fifth distribution, cjs + polyfill, which I really hope to avoid because supporting all those environments (web, node.js, cjs, esm, ts, ...) is already way too complex for the end users.

**Comment by dantman** [comment] 2021-12-13 22:37
> I created the branch [feat/webpack_ts](https://github.com/adaltas/node-csv/tree/feat/webpack_ts) with a `webpack` + TypeScript demo. `webpack` is configured with Node.js polyfill, I hope this is not a problem for you. Other than this, it works pretty and doesn't involve extra complexity.

Some environments like CRAv5 do not allow customizing WebPack and do not include Node.js polyfills. The lack of Node.js polyfills by default in bundlers is also intentional. The whole JS ecosystem is moving away from mocking Node.js packages and towards standard web APIs instead (even Node.js is adopting web apis). It would be a shame to have to configure an entire bundler plugin (or replace the bundler/framework itself) just because one wanted to do basic csv parsing/stringifying.

A full Node.js polyfill plugin doesn't even seem necessary. There are only 2 Node.js APIs that the csv packages use:

- `Buffer` - A polyfill plugin wouldn't be necessary for this at all if `import { Buffer } from 'buffer';` was used instead of all the files assuming that `Buffer` is available as a global. Heck the polyfill wouldn't even be necessary if Typed Arrays were used directly instead of Buffer (Typed Arrays are already available in Node.js).
- `streams` - All we need to figure out is some way to get the `stream` import to import `stream-browserify` instead. Or if we had WHATWG Streams (#242) this wouldn't be an issue at all.

**Comment by wdavidw** [comment] 2021-12-13 22:57
> It would be a shame to have to configure an entire bundler plugin (or replace the bundler/framework itself) just because one wanted to do basic csv parsing/stringifying.

This discussion is only relative to TypeScript, we already provide the ESM and IIFE distributions which don't require any polyfill. Don't you need a bundler anyway for TypeScript ?

**Comment by dantman** [comment] 2021-12-13 23:09
> Don't you need a bundler anyway for TypeScript ?

You do. But it would be a shame to have to add an entire plugin or drop CRA for another bundler, just because of one package.

> This discussion is only relative to TypeScript

That's  what confused me about recommending the WebPack config.

> we already provide the ESM and IIFE distributions which don't require any polyfill.

Doesn't seem to work in the CRAv5 Alpha with TypeScript.

- `import { stringify } from 'csv-stringify/browser/esm/sync'` leads to the same TypeScript error
- `import { stringify } from 'csv-stringify/sync'` leads to errors about Buffer not existing and missing streams

**Comment by wdavidw** [comment] 2021-12-14 08:45
I found a way with `csv-parse/browser/esm/index.js`, have a look at this [commit](https://github.com/adaltas/node-csv/commit/30a56eff8b2f50d3fb393ed463b69b59c50567a8), there is no more polyfill.

**Comment by dantman** [comment] 2021-12-14 09:41
`csv-stringify/browser/esm/index.js` seems fairly out of place when `csv-stringify/sync` is a valid import. Could we not have `exports` explicitly export `csv-stringify/browser/esm` and `csv-stringify/browser/esm/sync`?

Actually there isn't even any other browser export, why isn't the import just `csv-stringify/browser` and `csv-stringify/browser/sync`? Importing of ESM vs CJS is something that is supposed to be automatic based on what context it's imported from.

**Comment by wdavidw** [comment] 2021-12-24 08:46
> `csv-stringify/browser/esm/index.js` seems fairly out of place when `csv-stringify/sync` is a valid import.

Valid but not the same, one has polyfill, the other doesn't. Maybe there is a way with the `exports` filed to work around this or maybe someone will come with a better option but until then, we have to differentiate both.

> why isn't the import just csv-stringify/browser and csv-stringify/browser/sync? Importing of ESM vs CJS is something that is supposed to be automatic based on what context it's imported from.

You must define what browser do in such case, for example does it include polyfill or not or does it support package.json `export` field discovery.

> The simple act of parsing or generating a CSV doesn't inherently require any Node.js API.

No, but it needs to be stream based by default. Historically, the lib targeted Node.js environment and web streams didn't exist. Next efforts are going to focus and it. Just don't ever forget that none ever made a penny on it, it is all open source.

**Comment by dantman** [comment] 2021-12-24 11:09
> > `csv-stringify/browser/esm/index.js` seems fairly out of place when `csv-stringify/sync` is a valid import.
> 
> Valid but not the same, one has polyfill, the other doesn't. Maybe there is a way with the `exports` filed to work around this or maybe someone will come with a better option but until then, we have to differentiate both.

The reason the `.js` is not needed for `csv-stringify/sync` but required for `csv-stringify/browser/esm/index.js` is because [csv-stringify/package.json](https://github.com/adaltas/node-csv/blob/master/packages/csv-stringify/package.json) defines `"./sync": {"import": "./lib/sync.js", "require": "./dist/cjs/sync.cjs"}` for `csv-stringify/sync` but uses `"./browser/esm/*": "./dist/esm/*"` for `csv-stringify/browser/esm/sync`.

If `./browser/esm` and `./browser/esm/sync` were defined explicitly in `exports` the same way as `.` and `./sync` are defined then the `.js` would not be required.

> > why isn't the import just csv-stringify/browser and csv-stringify/browser/sync? Importing of ESM vs CJS is something that is supposed to be automatic based on what context it's imported from.
> 
> You must define which is the environment targeted by browser, for example does it include polyfill or not or does it support package.json `export` field discovery.

The `/browser` already covers the "does it include polyfill", there is no browser build without the polyfill. My point was that the `/esm` portion is redundant because even if there was a `/browser/cjs` the "ESM" or "CJS" targeting is already handled by the `{"import": "...", "require": "..."}` definition. And the code does not live at `node_modules/csv-stringify/browser/esm`, so old bundlers that don't support `"exports"` aren't relevant since they have to import `node_modules/csv-stringify/dist/esm` anyways.

Basically I am saying, why isn't csv-stringify's `"exports"` just:
```json
"exports": {
  ".": {
    "import": "./lib/index.js",
    "require": "./dist/cjs/index.cjs"
  },
  "./sync": {
    "import": "./lib/sync.js",
    "require": "./dist/cjs/sync.cjs"
  },
  "./browser": {
    "import": "./dist/esm/index.js"
  },
  "./browser/sync": {
    "import": "./dist/esm/sync.js"
  }
},
```

Which would allow for importing `csv-stringify/browser` and `csv-stringify/browser/sync`. Old bundlers are unaffected. The redundant `/esm` and `.js` aren't needed. And there's no conflict with a hypothetical CommonJS+Browser bundle since if that was ever made it would just be added as a `"require":`.

> > The simple act of parsing or generating a CSV doesn't inherently require any Node.js API.
> 
> No, but it needs to be stream based by default and need Buffer support. Historically, the lib targeted Node.js environment and web streams didn't exist. Next efforts are going to focus and it. Just don't ever forget that none ever made a penny on it, it is all open source.

Fair on the history. Though my point is that Buffer, Node.js streams, and web streams are not necessary as mandatory requirements to do basic csv parsing/stringifying.

Buffer is not necessary because ever since Node.js 3.x, Buffer is just a subclass of the Uint8Array typed array which browsers [near universally support](https://caniuse.com/typedarrays). In fact the Buffer polyfill mostly just adds the Node.js extras to the browser's Uint8Array. The library could just use `Uint8Array` directly and then the code runs in both Node.js and the browser without any Buffer polyfill. All you need is a `Uint8Array` polyfill if you have Internet Explorer 9 users. Which is easier to polyfill than Buffer and a project targeting IE<10 likely already has that polyfill.

Most of the browser use cases and even many of the Node.js use cases don't need streams. If streams were separate from the core implementation. i.e. Instead of `csv-stringify/sync` wrapping the stream implementation; if there were separate imports for `csv-stringify/stream` (Node.js streams), `csv-stringify/async` (promise/callback), `csv-stringify/sync`, `csv-stringify/web-streams` (web streams api in-browser), `csv-stringify/node-web-streams` (separate just because Node.js uses `import { ReadableStream } from 'node:stream/web'`) imports. Then importing `/sync` or the callback/promise API wouldn't import Node.js' `stream` API and wouldn't need a polyfill to be loaded for anyone that wasn't using the stream API.

Yes, I understand that the Node.js stream API cannot wrap the `/sync` API. But that doesn't mean that the `/sync` API has to be implemented using Node.js streams. It's possible for the core implementation to be something that's neither Node.js streams based nor the sync API. i.e. The core implementation could be implemented as A) a series of helper functions that handle the 90% of the library's code that doesn't actually use the Node.js streams API, or B) using a non-sync internal API either custom or based around something like the standard JS Generator API that works everywhere. Then both the sync API and streams API then just glue the internal implementation onto the Node.js streams and the sync API.

This is likely what the library is going to have to do anyways to implement the web streams API. Since `toWeb`/`fromWeb` probably isn't going to be part of the stream polyfill. And unlike with the Node.js stream API, the Web Stream API is async so you can't write a `/sync` implementation that just wraps the Web Stream API. It has to be a separate implementation.

**Comment by wdavidw** [comment] 2021-12-25 21:07
> csv-stringify/browser/esm/index.js seems fairly out of place when csv-stringify/sync is a valid import.

I have updated the exports fields to reflect your suggestions. You are right, this is more consistent with the rest.

**Comment by ivanoats** [comment] 2021-12-29 17:07
Would you have time to cut a release with these changes? I am wonder if it will help with testing with Jest and Typescript.

**Comment by wdavidw** [comment] 2021-12-29 22:15
Hi @ivanoats, I have pushed patched version of all packages with the changes. Keep me updated if this fixes your issue with Jest. I am closing this issue, we could always start a new one if necessary.

**Closed by wdavidw** 2021-12-29 22:15 UTC
