### ISSUE TITLE
Browser version of `csv-parse` doesn't work in JSDOM

### ISSUE THREAD

**Issue by illright** [adaltas/node-csv#370] opened 2022-11-28 12:54 UTC
**Describe the bug**

When I write tests that involve `csv-parse/browser/esm`, I encounter a bizarre error in the JSDOM environment with any call to `parse()` (e.g. `parse("test")`):

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
``` 

**To Reproduce**

Here's [a bare-bones project with Vitest](https://stackblitz.com/edit/vitest-dev-vitest-ugtiq7) that uses the JSDOM environment and creates this problem.  
**Note**: for some reason, it works correctly on StackBlitz, so download and run the project locally to see the issue. The command to run the test is `npm run test`.

Relevant bits:
```ts
// test/basic.test.ts
import { expect, test } from 'vitest';
import { parse } from 'csv-parse/browser/esm/sync';

test('CSV parse', () => {
  expect(parse('test')).toBeDefined();
});
```

```ts
// vite.config.ts
import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    environment: 'jsdom',
  },
});
```

**Additional context**

I've encountered this issue in both Node v16.18.1 and v19.1.0. I'm using the latest version of `csv-parse`, namely, 5.3.3.

The problem doesn't reproduce in a Node or Happy DOM environment.

**Comment by baublet** [comment] 2023-01-09 16:34
The issue is the Deno/Rollup shim fix:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/3482661/211359198-ed524a84-2440-4a19-af35-5b00d7d4c03a.png">

I was able to fix this in one line in the tests that utilize `csv-parse`:

```
// Anywhere near the top of your test file
global.setImmediate = (fn: any) => fn();
```

**Comment by MnHung** [comment] 2023-04-21 05:34
I believe I've encountered the same issue, the error message is:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
 ❯ fromObject node_modules/csv-parse/dist/esm/index.js:482:9
 ❯ from node_modules/csv-parse/dist/esm/index.js:314:10
 ❯ new Buffer node_modules/csv-parse/dist/esm/index.js:290:10
 ❯ Uint8Array.slice node_modules/csv-parse/dist/esm/index.js:1244:19
 ❯ Object.parse node_modules/csv-parse/dist/esm/index.js:5971:38
 ❯ Parser._transform node_modules/csv-parse/dist/esm/index.js:6379:26
 ❯ Parser.Transform._read node_modules/csv-parse/dist/esm/index.js:4929:10
 ❯ Parser.Transform._write node_modules/csv-parse/dist/esm/index.js:4917:83
 ❯ doWrite node_modules/csv-parse/dist/esm/index.js:4577:64

```

**Comment by MnHung** [comment] 2023-04-21 08:24
@illright my friend has tried passing `bom` option and it work, would you try this?

```
parse('test', { bom: true })
```

**Comment by wdavidw** [comment] 2023-05-17 21:18
This code is generated by rollup. I have never used vite but doesn't it take care of the dependencies, have your tried to import the default modules such as `import { parse } from 'csv-parse'` ?

**Comment by BenTopping** [comment] 2023-05-18 08:50
In my case I was testing files being parsed specifically with `import { parse } from 'csv-parse/browser/esm/sync'`. For anyone coming across this I ended up switching the environment for my specific test file to node using a vitest control comment`// @vitest-environment node` [docs here] (https://vitest.dev/guide/environment.html). As shown in my previous comment I think this bug lies with jsdom/vitest using their own ArrayBuffer instead of node's but Im not certain.

**Comment by wdavidw** [comment] 2023-05-18 20:51
Thank you for your feedback, closing now.

**Closed by wdavidw** 2023-05-18 20:51 UTC
